### ISSUE TITLE
Publish project website

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#10]
## Prerequisites

- [x] #3 must be done first
- [x] #30 must be done first

## Tasks

- Set everything required to run on the webserver of choice, including config files, replaces static content with environment variables, etc (e.g. `app.json`)
- Add example config files (e.g. `.env.example`)
- Add instructions to README on how to publish
- Open a pull request with the changes
- Publish the pull request branch on a server and add the link on the description 

Heroku (http://heroku.com/) is a good choice and easy option.

**Comment by paulodiovani** [comment]
Hi @JuarezLustosa,
Thanks for the pull request #28, but that is not how we want to do it.

- To publish a project on heroku we need to add a `Procfile` and optionally an `app.json`.
- It also requires an `npm start` script to init the web server, expecting a `$PORT` env var
- Heroku doesn't allow more than one web server on the same project, so I think we may need to create a route on our `backend` to serve static files under `dist/`
- Make sure to create a test project and publish the branch you're working on to check if it runs correctly
- We may want to wait for #4 to have something we can test

I'm suggesting Heroku because is the option I'm more familiar with, and because it has free limited plans which shall be enough for our needs. But feel free to choose whatever you like better.

**Comment by arabyalhomsi** [comment]
Agreed! and I think creating a route in our backend to serve the build is a good idea!

**Comment by JuarezLustosa** [comment]
@paulodiovani Ok thank guys, I'll wait for #4.

**Comment by arabyalhomsi** [comment]
I tried to publish the project and I ran into a problem. we need a redis server and you need to have a credit card on Heroku to be able to use one. I do not have a credit card.

**Comment by paulodiovani** [comment]
Whow, didn't know that.
I have an expired credit card and it allows setting up add-ons, but it won't if I remove it. :sweat_smile: 

@arabyalhomsi I have created a heroku app. Will publish once #34 and #40 are merged. :+1: 
I can create a _dev_ app and give you access if you let me know your heroku user/email.

**Comment by arabyalhomsi** [comment]
araby.ami@gmail.com

**Comment by paulodiovani** [comment]
I'll wait a bit more for #34, so we won't need an extra heroku app. :)

**Comment by arabyalhomsi** [comment]
@paulodiovani are we gonna publish this?

**Comment by paulodiovani** [comment]
@arabyalhomsi yes, I'll publish again once we fix https://github.com/paulodiovani/hacktoberrank/issues/45.

In the hurry I forgot to check this dependency on the pas PRs. :man_facepalming:

**Comment by paulodiovani** [comment]
Published at https://hacktoberrank-challenge.herokuapp.com/ :tada:
