### ISSUE TITLE
Apply recommended community standards.

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#11]
Github checklist for recommended community standards.

https://github.com/paulodiovani/hacktoberrank/community. 

- [x] Description
- [x] README
- [x] Code of conduct
- [x] Contributing
- [x] License
- [x] Issue templates
- [x] Pull request template

Open Pull requests accordingly.

**Comment by geektutor** [comment]
https://github.com/paulodiovani/hacktoberrank/pull/13

**Comment by paulodiovani** [comment]
There are still a few missing files to have all checks at https://github.com/paulodiovani/hacktoberrank/community. I'll add some suggestions here.

----

# Contributing

:+1: :tada: First off, thanks for taking the time to contribute! :tada: :+1: 

When contributing to this repository, please first discuss the change you wish to make via issue,
email, or any other method with the owners and former collaborators of this repository before making a change.

The [Issues section](https://github.com/paulodiovani/hacktoberrank/issues) is a good start to check what is needed. Alternatively, you can contribute with small changes, refactoring or improvements that don't have a related issue, in these cases you can just open a pull request.

Please note we have a code of conduct, please follow it in all your interactions with the project.
You can read the code of conduct at https://github.com/paulodiovani/hacktoberrank/blob/master/CODE_OF_CONDUCT.md.

## Pull Request Process

1. Add a description about what the pull request changes or fixes
1. Ensure the pull request branch can be run following the instructions on README and won't break build and tests in CI.
1. Write unit tests for new features.
1. New e2e tests are also welcome but can be written on a separate PR.
1. Update the README.md with details of changes, if any, including setup/run instructions, interface, etc.
1. Be kind when discussing changes on pull requests.
1. Pull Requests are required to be approved at least once to be merged. This process can take a while so be patient.

## Other ways of contributing

- Report bugs or suggest features by writing issues
- Review and test pull requests by other contributors
- Spread the word about this project so we can achieve the [challenge](https://github.com/paulodiovani/hacktoberrank/issues/1) :speaking_head: 

----

# Pull request template

Detailed changes description...
What this PRs adds or improve in the project.

## Is this related to an issue?

Issue #[number] or link.

## How to run and see the changes?

1. Clone this pull request branch
1. Follow setup instructions on README
1. Additional steps...

## Do we have any screenshots?

![screnshot 001](http://example.com/some-image)

**Comment by paulodiovani** [comment]
review and suggestions, please: https://github.com/paulodiovani/hacktoberrank/pull/24

**Comment by arabyalhomsi** [comment]
Can we have the coverage report tag? the one that says how much code we covered in our tests?

**Comment by paulodiovani** [comment]
> Can we have the coverage report tag? the one that says how much code we covered in our tests?

Good idea. :)
