### ISSUE TITLE
Use standardjs rules for linter

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#18]
Lets use [Standard JS](https://standardjs.com) rules for eslint.
This can be achieved by adding `extends: 'standard'` to `.eslintrc.js` and adding the required dependencies to `package.json` (to `devDependencies`).

More details in https://github.com/standard/eslint-config-standard

- [x] extend standardjs rules
- [x] add standardjs dependencies
- [x] fix javascript files (`eslint --fix` should do for most of the cases)

**Comment by danielharvilik** [comment]
Hey!,, is it available ?
