### ISSUE TITLE
Add .npmrc with default npm registry

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#19]
Some companies use a custom npm registry set at `~/.npmrc`. 

To prevent failures on npm install, let's add our own `.npmrc` to the project.
A simple registry line is enough.

```
registry=https://registry.npmjs.org/
```

**Comment by adarshlilha** [comment]
Hey, can I take this?

**Comment by paulodiovani** [comment]
Sure. :)
