### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#2]
Add a README describing the project intention and challenge.

Note: See other issues for details.

**Comment by paulodiovani** [comment]
## Project description:

Hacktober Rank is a rank of participants of the Hacktoberfest. It fetches pull requests from github and list the users with most opened pull requests during the event period: _October 1st to October 31_.

The rank page lists the rank per year and allows to filter by location.

**Comment by Syl1405** [comment]
Hi,I would like to work on this issue :)
