### ISSUE TITLE
Booststrap the project

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#3]
Bootstrap the initial project, which shall include:

- a working webserver
- a landing page
- a test suite (a single dumb passing test is enough)
- a `.gitignore` to match the language and framework of choice

----

The language and framework could be any fairly popular language.
I suggest Ruby or Node.js which are the ones I'm more used to work and will ease my reviews.

**Comment by arabyalhomsi** [comment]
Can I be assinged to this? I would sit it up using nodejs (express or sailsjs maybe) and vuejs. What do you think?

**Comment by sayanmondal2098** [comment]
Hi! i wanna to start with you .. Please push a file as we can start . Thanks

**Comment by arabyalhomsi** [comment]
I would finish this by tonight actuallly, I cannot start working on this right away. Is that a problem?

**Comment by paulodiovani** [comment]
That's great guys. :D

@arabyalhomsi I prefer a pure express backe-end, to keep it simple.
Sails.js can be a bit confusing for starters.

Also, note we don't care about databases yet.

vue.js for front-end would be great.

**Comment by arabyalhomsi** [comment]
Sounds great! As I said I won't be able to do anything until 4-5 hours so if someone would want to do this, that's fine.

**Comment by paulodiovani** [comment]
Done in #17
