### ISSUE TITLE
Serve the front-end from the back-end

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#30]
If we publish to heroku, we need a single webserver, listening to `$PORT`.

So let's use express static feature to host the front-end build on `dist/`
Also...

- change `serve-backend` script to `start`
- add `npm run build` to `prestart` script

**Comment by Luiginator** [comment]
I would like to work on this.

**Comment by Luiginator** [comment]
My PR is ready but I am getting a 403 when I try to push my branch. Could you give me access rights?

**Comment by Luiginator** [comment]
@paulodiovani I implemented everything that was requested in this issue. Could you please take a look? Thank you!

**Comment by paulodiovani** [comment]
@Luiginator closed the PR before merging. :disappointed: 
It was almost done.

Can someone else take over?

**Comment by arabyalhomsi** [comment]
I will do it, sure @paulodiovani
