### ISSUE TITLE
Improve fix linter for CI

### ISSUE THREAD

**Issue by paulodiovani** [paulodiovani/hacktoberrank#35]
There are some changes we should do to improve our code lint.

- [ ] do not fix linter errors or warnings
- [ ] do not allow warnings
- [ ] change `no-console`/`no-debugger` rules
  + add `debug` (https://www.npmjs.com/package/debug) module and use it instead of `console.log`
- [ ] prefer const when not reassign
- [ ] lint `tests/` folder as well
- [ ] fix new issues fond

This can be achieved by adding or changing:

```js
// in package.json
"lint": "vue-cli-service lint --no-fix --max-warnings 0 src/ backend/ tests/"
```

```js
// in .eslintrc.js
rules: {
  'no-console': 'warn',
  'no-debugger': 'warn',
  'prefer-const': 'error',
},
```

**Comment by hirohaji** [comment]
I'm working on this
